/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

var a = 0,b=1,f=1;
for(var i = 0; i<100; i++){
	f = a+b;
	a = b; 
	b = f;
	console.log(f);
}

var a = 0, b=1,f=1;
do{
	f = a+b;
	a = b;
	b = f;
	
}console.log(f);
while(f <= 4000000)


//Correct One

var a = 0, b=1,f=1,sum=0;
while(f < 4000000){
	f = a+b;
	a = b;
	b = f;
	console.log(f);
	if(f%2 === 0){
		sum += f;
	}
}

console.log(sum);



